# Generated by Django 6.0.1 on 2026-01-11 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_step_completed', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['user', 'lesson'], name='progress_tr_user_id_334c33_idx'), models.Index(fields=['completed'], name='progress_tr_complet_040b3a_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
