# Generated by Django 6.0.1 on 2026-01-11 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('upi', 'UPI'), ('basic', 'Basic')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('estimated_duration', models.IntegerField(default=5, help_text='Duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['category', 'language'], name='lessons_les_categor_193e1a_idx'), models.Index(fields=['is_active'], name='lessons_les_is_acti_ea1d9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('instruction_text', models.TextField()),
                ('step_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('simulation', 'Simulation'), ('quiz', 'Quiz')], default='text', max_length=20)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_caption', models.CharField(blank=True, max_length=255)),
                ('estimated_duration', models.IntegerField(default=30, help_text='Duration in seconds')),
                ('is_interactive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lessons.lesson')),
            ],
            options={
                'ordering': ['lesson', 'step_number'],
                'unique_together': {('lesson', 'step_number')},
            },
        ),
    ]
